#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define INDI_RPICAM2_VERSION_MAJOR @INDI_RPICAM2_VERSION_MAJOR@
#define INDI_RPICAM2_VERSION_MINOR @INDI_RPICAM2_VERSION_MAJOR@

#endif // CONFIG_H